version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ytestbook
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - .:/code
