---
openapi: 3.0.2
info:
  title: yTestbook
  version: 1.0.0
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      tags:
        - yTestbook
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
          description: User logged successfully
      operationId: userLogin
  /testbook/all:
    get:
      tags:
        - yTestbook
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TestbookResponse"
          description: List of all testbook
  /testbook/:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestbookRequest"
        required: true
      tags:
        - yTestbook
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestbookResponse"
          description: Testbook created successfully
  /testcase/all:
    get:
      tags:
        - yTestbook
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TestcaseResponse"
          description: Get all testcases
components:
  schemas:
    LoginRequest:
      title: Root Type for LoginRequest
      description: ""
      required:
        - password
        - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: admin
        password: admin
    LoginResponse:
      title: Root Type for LoginResponse
      description: ""
      type: object
      properties:
        accessToken:
          type: string
      example:
        accessToken: string
    TestbookResponse:
      title: Root Type for TestbookResponse
      description: ""
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        client:
          type: string
        lastEdit:
          type: string
      example:
        id: asd
        name: string
        client: string
        lastEdit: string
    TestbookRequest:
      title: Root Type for TestbookRequest
      description: ""
      type: object
      properties:
        name:
          type: string
        client:
          type: string
      example:
        name: string
        client: string
    TestcaseResponse:
      title: Root Type for TestcaseResponse
      description: ""
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          $ref: "#/components/schemas/StatusEnum"
        requirements:
          description: ""
          type: string
        description:
          description: ""
          type: string
        startDate:
          description: ""
          type: string
        endDate:
          description: ""
          type: string
        test:
          description: ""
          type: array
          items:
            $ref: "#/components/schemas/TestResponse"
        tag:
          description: ""
          type: array
          items:
            $ref: "#/components/schemas/TagResponse"
      example:
        id: some text
        title: some text
        status: some text
    TestResponse:
      title: Root Type for TestResponse
      description: ""
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          $ref: "#/components/schemas/StatusEnum"
        description:
          description: ""
          type: string
        requirements:
          description: ""
          type: string
        input:
          description: ""
          type: string
        output:
          description: ""
          type: string
        tag:
          description: ""
          type: array
          items:
            $ref: "#/components/schemas/TagResponse"
      example:
        id: "1"
        title: string
        priority: string
    TagResponse:
      title: Root Type for FaqResponse
      description: "    "
      type: object
      properties:
        id:
          type: string
        title:
          type: string
      example:
        id: "1"
        title: string
    StatusEnum:
      description: ""
      enum:
        - BLOCKED
        - CANCELLED
        - DONE
        - FAIL
        - PAUSED
        - PENDING
        - TODO
      type: string
